// create-nfts/part-2/src/App.svelte
<script lang="ts">
  import { BeaconWallet } from "@taquito/beacon-wallet";
  import { NetworkType } from "@airgap/beacon-types";
  import { TezosToolkit, MichelsonMap } from "@taquito/taquito";
  import { stringToBytes } from "@taquito/utils";

  const rpcUrl = "https://rpc.ghostnet.teztnets.com";
  const Tezos = new TezosToolkit(rpcUrl);

  let wallet;
  let address;
  let balance;
  let statusMessage = "Connect your wallet.";
  let buttonActive = false;

  const connectWallet = async () => {
    try {
      const newWallet = new BeaconWallet({
        name: "NFT app tutorial",
        network: {
          type: NetworkType.GHOSTNET,
        },
      });
      await newWallet.requestPermissions();
      address = await newWallet.getPKH();
      const balanceMutez = await Tezos.tz.getBalance(address);
      balance = balanceMutez.div(1000000).toFormat(2);
      buttonActive = true;
      statusMessage = "Wallet connected. Ready to mint NFTs.";
      wallet = newWallet;
    } catch (error) {
      console.error("Error connecting wallet:", error);
    }
  };

  const disconnectWallet = () => {
    wallet.client.clearActiveAccount();
    statusMessage = "Connect your wallet.";
    wallet = undefined;
    buttonActive = false;
  };
</script>

<main>
  <h1>Create NFTs</h1>

  <div class="card">
    {#if wallet}
      <p>The address of the connected wallet is {address}.</p>
      <p>Its balance in tez is {balance}.</p>
      <button on:click={disconnectWallet}>Disconnect wallet</button>
    {:else}
      <button on:click={connectWallet}>Connect wallet</button>
    {/if}
    <p>{statusMessage}</p>
  </div>
</main>

<style>
</style>

// dapp/part-1/frontend/src/App.tsx
import "./init";
import { NetworkType } from '@airgap/beacon-types';
import { BeaconWallet } from '@taquito/beacon-wallet';
import { TezosToolkit } from '@taquito/taquito';
import * as api from '@tzkt/sdk-api';
import { useEffect, useState } from 'react';
import './App.css';
import ConnectButton from './ConnectWallet';
import DisconnectButton from './DisconnectWallet';
import { type PokeGameWalletType } from './pokeGame.types';

function App() {
  api.defaults.baseUrl = 'https://api.ghostnet.tzkt.io';

  const [Tezos, setTezos] = useState<TezosToolkit>(
    new TezosToolkit('https://rpc.ghostnet.teztnets.com')
  );
  const [wallet, setWallet] = useState<BeaconWallet>(
    new BeaconWallet({
      name: 'Poke game',
      network: {
        type: NetworkType.GHOSTNET,
      }
    })
  );
  Tezos.setWalletProvider(wallet);

  useEffect(() => {
    (async () => {
      const activeAccount = await wallet.client.getActiveAccount();
      if (activeAccount) {
        setUserAddress(activeAccount.address);
        const balanceMutez = await Tezos.tz.getBalance(activeAccount.address);
        const balanceTez = balanceMutez.toNumber() / 10000000;
        setUserBalance(balanceTez);
      }
    })();
  }, []);

  const [userAddress, setUserAddress] = useState<string>('');
  const [balanceTez, setUserBalance] = useState<number>(0);
  const [contracts, setContracts] = useState<Array<api.Contract>>([]);

  const fetchContracts = () => {
    (async () => {
      setContracts(
        await api.contractsGetSimilar(import.meta.env.VITE_CONTRACT_ADDRESS, {
          includeStorage: true,
          sort: { desc: 'id' },
        })
      );
    })();
  };

  const poke = async (contract: api.Contract) => {
    let c: PokeGameWalletType = await Tezos.wallet.at<PokeGameWalletType>(
      '' + contract.address
    );
    try {
      const op = await c.methodsObject.default().send();
      await op.confirmation();
      alert('Tx done');
    } catch (error: any) {
      console.table(`Error: ${JSON.stringify(error, null, 2)}`);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <ConnectButton
          Tezos={Tezos}
          setTezos={setTezos}
          setUserAddress={setUserAddress}
          setUserBalance={setUserBalance}
          wallet={wallet}
        />

        <DisconnectButton
          wallet={wallet}
          setUserAddress={setUserAddress}
          setUserBalance={setUserBalance}
        />

        <div>
          {userAddress ?
              `I am ${userAddress} with ${balanceTez} tez`
            : `Click "Connect with wallet."`
          }
        </div>
        <br />
        <button onClick={fetchContracts}>Fetch contracts</button>
        <table>
          <thead>
            <tr>
              <th>Contract address</th>
              <th>Pokes and messages</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {contracts.map((contract, index) => <tr key={index}><td style={{borderStyle: "dotted"}}>{contract.address}</td><td style={{borderStyle: "dotted"}}>{contract.storage.join(", ")}</td><td style={{borderStyle: "dotted"}}><button onClick={() => poke(contract)}>Poke</button></td></tr>)}
          </tbody>
        </table>
      </header>
    </div>
  );
}

export default App;
